let trial_objects = [
    {
        "id": 0,
        "conj1": "I",
        "conj2": "we",
        "predicate": "eating the cake.",
        "text": "Either I or we %is,are,am% eating the cake.",
        "conj1_agr": "1S",
        "conj2_agr": "1P",
        "dataType": "critical",
        "cond": "1S_or_1P"
    },
    {
        "id": 1,
        "conj1": "I",
        "conj2": "we",
        "predicate": "going to the beach.",
        "text": "Either I or we %is,are,am% going to the beach.",
        "conj1_agr": "1S",
        "conj2_agr": "1P",
        "dataType": "critical",
        "cond": "1S_or_1P"
    },
    {
        "id": 2,
        "conj1": "I",
        "conj2": "we",
        "predicate": "objecting to the wedding.",
        "text": "Either I or we %is,are,am% objecting to the wedding.",
        "conj1_agr": "1S",
        "conj2_agr": "1P",
        "dataType": "critical",
        "cond": "1S_or_1P"
    },
    {
        "id": 3,
        "conj1": "I",
        "conj2": "we",
        "predicate": "running a marathon.",
        "text": "Either I or we %is,are,am% running a marathon.",
        "conj1_agr": "1S",
        "conj2_agr": "1P",
        "dataType": "critical",
        "cond": "1S_or_1P"
    },
    {
        "id": 4,
        "conj1": "I",
        "conj2": "we",
        "predicate": "painting a masterpiece.",
        "text": "Either I or we %is,are,am% painting a masterpiece.",
        "conj1_agr": "1S",
        "conj2_agr": "1P",
        "dataType": "critical",
        "cond": "1S_or_1P"
    },
    {
        "id": 5,
        "conj1": "I",
        "conj2": "the harpy",
        "predicate": "celebrating World Rivers Day.",
        "text": "Either I or the harpy %is,are,am% celebrating World Rivers Day.",
        "conj1_agr": "1S",
        "conj2_agr": "3S",
        "dataType": "critical",
        "cond": "1S_or_3S"
    },
    {
        "id": 6,
        "conj1": "I",
        "conj2": "the columnist",
        "predicate": "watching the movie.",
        "text": "Either I or the columnist %is,are,am% watching the movie.",
        "conj1_agr": "1S",
        "conj2_agr": "3S",
        "dataType": "critical",
        "cond": "1S_or_3S"
    },
    {
        "id": 7,
        "conj1": "I",
        "conj2": "the singer",
        "predicate": "grading the term papers.",
        "text": "Either I or the singer %is,are,am% grading the term papers.",
        "conj1_agr": "1S",
        "conj2_agr": "3S",
        "dataType": "critical",
        "cond": "1S_or_3S"
    },
    {
        "id": 8,
        "conj1": "I",
        "conj2": "the painter",
        "predicate": "preheating the oven.",
        "text": "Either I or the painter %is,are,am% preheating the oven.",
        "conj1_agr": "1S",
        "conj2_agr": "3S",
        "dataType": "critical",
        "cond": "1S_or_3S"
    },
    {
        "id": 9,
        "conj1": "I",
        "conj2": "the banshee",
        "predicate": "helping others.",
        "text": "Either I or the banshee %is,are,am% helping others.",
        "conj1_agr": "1S",
        "conj2_agr": "3S",
        "dataType": "critical",
        "cond": "1S_or_3S"
    },
    {
        "id": 10,
        "conj1": "I",
        "conj2": "the city councilmembers",
        "predicate": "asking for assistance.",
        "text": "Either I or the city councilmembers %is,are,am% asking for assistance.",
        "conj1_agr": "1S",
        "conj2_agr": "3P",
        "dataType": "critical",
        "cond": "1S_or_3P"
    },
    {
        "id": 11,
        "conj1": "I",
        "conj2": "the robots",
        "predicate": "going grocery shopping.",
        "text": "Either I or the robots %is,are,am% going grocery shopping.",
        "conj1_agr": "1S",
        "conj2_agr": "3P",
        "dataType": "critical",
        "cond": "1S_or_3P"
    },
    {
        "id": 12,
        "conj1": "I",
        "conj2": "the altos",
        "predicate": "going to the moon.",
        "text": "Either I or the altos %is,are,am% going to the moon.",
        "conj1_agr": "1S",
        "conj2_agr": "3P",
        "dataType": "critical",
        "cond": "1S_or_3P"
    },
    {
        "id": 13,
        "conj1": "I",
        "conj2": "the children",
        "predicate": "drinking copious amounts of lemonade.",
        "text": "Either I or the children %is,are,am% drinking copious amounts of lemonade.",
        "conj1_agr": "1S",
        "conj2_agr": "3P",
        "dataType": "critical",
        "cond": "1S_or_3P"
    },
    {
        "id": 14,
        "conj1": "I",
        "conj2": "the jugglers",
        "predicate": "helping the team win.",
        "text": "Either I or the jugglers %is,are,am% helping the team win.",
        "conj1_agr": "1S",
        "conj2_agr": "3P",
        "dataType": "critical",
        "cond": "1S_or_3P"
    },
    {
        "id": 15,
        "conj1": "we",
        "conj2": "I",
        "predicate": "making a hearty stew.",
        "text": "Either we or I %is,are,am% making a hearty stew.",
        "conj1_agr": "1P",
        "conj2_agr": "1S",
        "dataType": "critical",
        "cond": "1P_or_1S"
    },
    {
        "id": 16,
        "conj1": "we",
        "conj2": "I",
        "predicate": "building the Lego set.",
        "text": "Either we or I %is,are,am% building the Lego set.",
        "conj1_agr": "1P",
        "conj2_agr": "1S",
        "dataType": "critical",
        "cond": "1P_or_1S"
    },
    {
        "id": 17,
        "conj1": "we",
        "conj2": "I",
        "predicate": "signing up for karaoke.",
        "text": "Either we or I %is,are,am% signing up for karaoke.",
        "conj1_agr": "1P",
        "conj2_agr": "1S",
        "dataType": "critical",
        "cond": "1P_or_1S"
    },
    {
        "id": 18,
        "conj1": "we",
        "conj2": "I",
        "predicate": "winning the tournament.",
        "text": "Either we or I %is,are,am% winning the tournament.",
        "conj1_agr": "1P",
        "conj2_agr": "1S",
        "dataType": "critical",
        "cond": "1P_or_1S"
    },
    {
        "id": 19,
        "conj1": "we",
        "conj2": "I",
        "predicate": "ordering more paella.",
        "text": "Either we or I %is,are,am% ordering more paella.",
        "conj1_agr": "1P",
        "conj2_agr": "1S",
        "dataType": "critical",
        "cond": "1P_or_1S"
    },
    {
        "id": 20,
        "conj1": "we",
        "conj2": "the assailant",
        "predicate": "building a house.",
        "text": "Either we or the assailant %is,are,am% building a house.",
        "conj1_agr": "1P",
        "conj2_agr": "3S",
        "dataType": "critical",
        "cond": "1P_or_3S"
    },
    {
        "id": 21,
        "conj1": "we",
        "conj2": "the engineer",
        "predicate": "investing in cryptocurrency.",
        "text": "Either we or the engineer %is,are,am% investing in cryptocurrency.",
        "conj1_agr": "1P",
        "conj2_agr": "3S",
        "dataType": "critical",
        "cond": "1P_or_3S"
    },
    {
        "id": 22,
        "conj1": "we",
        "conj2": "the neighbor",
        "predicate": "traveling the world.",
        "text": "Either we or the neighbor %is,are,am% traveling the world.",
        "conj1_agr": "1P",
        "conj2_agr": "3S",
        "dataType": "critical",
        "cond": "1P_or_3S"
    },
    {
        "id": 23,
        "conj1": "we",
        "conj2": "the taste tester",
        "predicate": "listening to Taylor's new album.",
        "text": "Either we or the taste tester %is,are,am% listening to Taylor's new album.",
        "conj1_agr": "1P",
        "conj2_agr": "3S",
        "dataType": "critical",
        "cond": "1P_or_3S"
    },
    {
        "id": 24,
        "conj1": "we",
        "conj2": "the emperor",
        "predicate": "writing a novel.",
        "text": "Either we or the emperor %is,are,am% writing a novel.",
        "conj1_agr": "1P",
        "conj2_agr": "3S",
        "dataType": "critical",
        "cond": "1P_or_3S"
    },
    {
        "id": 25,
        "conj1": "we",
        "conj2": "the lizard people",
        "predicate": "looking for the meaning of life.",
        "text": "Either we or the lizard people %is,are,am% looking for the meaning of life.",
        "conj1_agr": "1P",
        "conj2_agr": "3P",
        "dataType": "critical",
        "cond": "1P_or_3P"
    },
    {
        "id": 26,
        "conj1": "we",
        "conj2": "the reporters",
        "predicate": "celebrating the team's win.",
        "text": "Either we or the reporters %is,are,am% celebrating the team's win.",
        "conj1_agr": "1P",
        "conj2_agr": "3P",
        "dataType": "critical",
        "cond": "1P_or_3P"
    },
    {
        "id": 27,
        "conj1": "we",
        "conj2": "the diplomats",
        "predicate": "running for public office.",
        "text": "Either we or the diplomats %is,are,am% running for public office.",
        "conj1_agr": "1P",
        "conj2_agr": "3P",
        "dataType": "critical",
        "cond": "1P_or_3P"
    },
    {
        "id": 28,
        "conj1": "we",
        "conj2": "the ladies",
        "predicate": "exploring the ocean depths.",
        "text": "Either we or the ladies %is,are,am% exploring the ocean depths.",
        "conj1_agr": "1P",
        "conj2_agr": "3P",
        "dataType": "critical",
        "cond": "1P_or_3P"
    },
    {
        "id": 29,
        "conj1": "we",
        "conj2": "the customers",
        "predicate": "baking cookies.",
        "text": "Either we or the customers %is,are,am% baking cookies.",
        "conj1_agr": "1P",
        "conj2_agr": "3P",
        "dataType": "critical",
        "cond": "1P_or_3P"
    },
    {
        "id": 30,
        "conj1": "the politician",
        "conj2": "I",
        "predicate": "debating morality with the guru.",
        "text": "Either the politician or I %is,are,am% debating morality with the guru.",
        "conj1_agr": "3S",
        "conj2_agr": "1S",
        "dataType": "critical",
        "cond": "3S_or_1S"
    },
    {
        "id": 31,
        "conj1": "the firefighter",
        "conj2": "I",
        "predicate": "touring the San Diego Zoo.",
        "text": "Either the firefighter or I %is,are,am% touring the San Diego Zoo.",
        "conj1_agr": "3S",
        "conj2_agr": "1S",
        "dataType": "critical",
        "cond": "3S_or_1S"
    },
    {
        "id": 32,
        "conj1": "the fisherman",
        "conj2": "I",
        "predicate": "ordering for the table.",
        "text": "Either the fisherman or I %is,are,am% ordering for the table.",
        "conj1_agr": "3S",
        "conj2_agr": "1S",
        "dataType": "critical",
        "cond": "3S_or_1S"
    },
    {
        "id": 33,
        "conj1": "the clown",
        "conj2": "I",
        "predicate": "asking for more coffee.",
        "text": "Either the clown or I %is,are,am% asking for more coffee.",
        "conj1_agr": "3S",
        "conj2_agr": "1S",
        "dataType": "critical",
        "cond": "3S_or_1S"
    },
    {
        "id": 34,
        "conj1": "the warrior",
        "conj2": "I",
        "predicate": "beginning to believe in luck.",
        "text": "Either the warrior or I %is,are,am% beginning to believe in luck.",
        "conj1_agr": "3S",
        "conj2_agr": "1S",
        "dataType": "critical",
        "cond": "3S_or_1S"
    },
    {
        "id": 35,
        "conj1": "the field worker",
        "conj2": "we",
        "predicate": "fixing the car.",
        "text": "Either the field worker or we %is,are,am% fixing the car.",
        "conj1_agr": "3S",
        "conj2_agr": "1P",
        "dataType": "critical",
        "cond": "3S_or_1P"
    },
    {
        "id": 36,
        "conj1": "the librarian",
        "conj2": "we",
        "predicate": "petting the cat.",
        "text": "Either the librarian or we %is,are,am% petting the cat.",
        "conj1_agr": "3S",
        "conj2_agr": "1P",
        "dataType": "critical",
        "cond": "3S_or_1P"
    },
    {
        "id": 37,
        "conj1": "the coach",
        "conj2": "we",
        "predicate": "reading the latest Stephen King novel.",
        "text": "Either the coach or we %is,are,am% reading the latest Stephen King novel.",
        "conj1_agr": "3S",
        "conj2_agr": "1P",
        "dataType": "critical",
        "cond": "3S_or_1P"
    },
    {
        "id": 38,
        "conj1": "the cyclist",
        "conj2": "we",
        "predicate": "running the meeting.",
        "text": "Either the cyclist or we %is,are,am% running the meeting.",
        "conj1_agr": "3S",
        "conj2_agr": "1P",
        "dataType": "critical",
        "cond": "3S_or_1P"
    },
    {
        "id": 39,
        "conj1": "the gamer",
        "conj2": "we",
        "predicate": "teaching a class.",
        "text": "Either the gamer or we %is,are,am% teaching a class.",
        "conj1_agr": "3S",
        "conj2_agr": "1P",
        "dataType": "critical",
        "cond": "3S_or_1P"
    },
    {
        "id": 40,
        "conj1": "the architect",
        "conj2": "the visitor",
        "predicate": "camping in the Redwood forest.",
        "text": "Either the architect or the visitor %is,are,am% camping in the Redwood forest.",
        "conj1_agr": "3S",
        "conj2_agr": "3S",
        "dataType": "critical",
        "cond": "3S_or_3S"
    },
    {
        "id": 41,
        "conj1": "the journalist",
        "conj2": "the innkeeper",
        "predicate": "sunbathing on the beach.",
        "text": "Either the journalist or the innkeeper %is,are,am% sunbathing on the beach.",
        "conj1_agr": "3S",
        "conj2_agr": "3S",
        "dataType": "critical",
        "cond": "3S_or_3S"
    },
    {
        "id": 42,
        "conj1": "the writer",
        "conj2": "the pilot",
        "predicate": "dancing the Hula.",
        "text": "Either the writer or the pilot %is,are,am% dancing the Hula.",
        "conj1_agr": "3S",
        "conj2_agr": "3S",
        "dataType": "critical",
        "cond": "3S_or_3S"
    },
    {
        "id": 43,
        "conj1": "the diver",
        "conj2": "the miner",
        "predicate": "listening to the tale of Odysseus.",
        "text": "Either the diver or the miner %is,are,am% listening to the tale of Odysseus.",
        "conj1_agr": "3S",
        "conj2_agr": "3S",
        "dataType": "critical",
        "cond": "3S_or_3S"
    },
    {
        "id": 44,
        "conj1": "the fairy",
        "conj2": "the astronaut",
        "predicate": "writing an original song about breakups.",
        "text": "Either the fairy or the astronaut %is,are,am% writing an original song about breakups.",
        "conj1_agr": "3S",
        "conj2_agr": "3S",
        "dataType": "critical",
        "cond": "3S_or_3S"
    },
    {
        "id": 45,
        "conj1": "the Grim Reaper",
        "conj2": "the astrologists",
        "predicate": "cleaning the inside of the oven.",
        "text": "Either the Grim Reaper or the astrologists %is,are,am% cleaning the inside of the oven.",
        "conj1_agr": "3S",
        "conj2_agr": "3P",
        "dataType": "critical",
        "cond": "3S_or_3P"
    },
    {
        "id": 46,
        "conj1": "the surfer",
        "conj2": "the ensemble members",
        "predicate": "climbing a mountain.",
        "text": "Either the surfer or the ensemble members %is,are,am% climbing a mountain.",
        "conj1_agr": "3S",
        "conj2_agr": "3P",
        "dataType": "critical",
        "cond": "3S_or_3P"
    },
    {
        "id": 47,
        "conj1": "the police officer",
        "conj2": "the cashiers",
        "predicate": "voting in favor of the proposition.",
        "text": "Either the police officer or the cashiers %is,are,am% voting in favor of the proposition.",
        "conj1_agr": "3S",
        "conj2_agr": "3P",
        "dataType": "critical",
        "cond": "3S_or_3P"
    },
    {
        "id": 48,
        "conj1": "the teacher",
        "conj2": "the hairdressers",
        "predicate": "crying in the club.",
        "text": "Either the teacher or the hairdressers %is,are,am% crying in the club.",
        "conj1_agr": "3S",
        "conj2_agr": "3P",
        "dataType": "critical",
        "cond": "3S_or_3P"
    },
    {
        "id": 49,
        "conj1": "the gremlin",
        "conj2": "the zoologists",
        "predicate": "designing a website.",
        "text": "Either the gremlin or the zoologists %is,are,am% designing a website.",
        "conj1_agr": "3S",
        "conj2_agr": "3P",
        "dataType": "critical",
        "cond": "3S_or_3P"
    },
    {
        "id": 50,
        "conj1": "the wizards",
        "conj2": "I",
        "predicate": "writing a review of the circus performance.",
        "text": "Either the wizards or I %is,are,am% writing a review of the circus performance.",
        "conj1_agr": "3P",
        "conj2_agr": "1S",
        "dataType": "critical",
        "cond": "3P_or_1S"
    },
    {
        "id": 51,
        "conj1": "the maids",
        "conj2": "I",
        "predicate": "making a difference.",
        "text": "Either the maids or I %is,are,am% making a difference.",
        "conj1_agr": "3P",
        "conj2_agr": "1S",
        "dataType": "critical",
        "cond": "3P_or_1S"
    },
    {
        "id": 52,
        "conj1": "the angels",
        "conj2": "I",
        "predicate": "hitchhiking to British Columbia.",
        "text": "Either the angels or I %is,are,am% hitchhiking to British Columbia.",
        "conj1_agr": "3P",
        "conj2_agr": "1S",
        "dataType": "critical",
        "cond": "3P_or_1S"
    },
    {
        "id": 53,
        "conj1": "the cartoonists",
        "conj2": "I",
        "predicate": "attending the conference in Azerbaijan.",
        "text": "Either the cartoonists or I %is,are,am% attending the conference in Azerbaijan.",
        "conj1_agr": "3P",
        "conj2_agr": "1S",
        "dataType": "critical",
        "cond": "3P_or_1S"
    },
    {
        "id": 54,
        "conj1": "the programmers",
        "conj2": "I",
        "predicate": "conducting an experiment.",
        "text": "Either the programmers or I %is,are,am% conducting an experiment.",
        "conj1_agr": "3P",
        "conj2_agr": "1S",
        "dataType": "critical",
        "cond": "3P_or_1S"
    },
    {
        "id": 55,
        "conj1": "the mummies",
        "conj2": "we",
        "predicate": "welcoming the guests.",
        "text": "Either the mummies or we %is,are,am% welcoming the guests.",
        "conj1_agr": "3P",
        "conj2_agr": "1P",
        "dataType": "critical",
        "cond": "3P_or_1P"
    },
    {
        "id": 56,
        "conj1": "the professors",
        "conj2": "we",
        "predicate": "visiting the capital of Lithuania.",
        "text": "Either the professors or we %is,are,am% visiting the capital of Lithuania.",
        "conj1_agr": "3P",
        "conj2_agr": "1P",
        "dataType": "critical",
        "cond": "3P_or_1P"
    },
    {
        "id": 57,
        "conj1": "the jewelers",
        "conj2": "we",
        "predicate": "giving away free donuts.",
        "text": "Either the jewelers or we %is,are,am% giving away free donuts.",
        "conj1_agr": "3P",
        "conj2_agr": "1P",
        "dataType": "critical",
        "cond": "3P_or_1P"
    },
    {
        "id": 58,
        "conj1": "the dog trainers",
        "conj2": "we",
        "predicate": "inspiring others.",
        "text": "Either the dog trainers or we %is,are,am% inspiring others.",
        "conj1_agr": "3P",
        "conj2_agr": "1P",
        "dataType": "critical",
        "cond": "3P_or_1P"
    },
    {
        "id": 59,
        "conj1": "the nutritionists",
        "conj2": "we",
        "predicate": "calling for help.",
        "text": "Either the nutritionists or we %is,are,am% calling for help.",
        "conj1_agr": "3P",
        "conj2_agr": "1P",
        "dataType": "critical",
        "cond": "3P_or_1P"
    },
    {
        "id": 60,
        "conj1": "the hitchhikers",
        "conj2": "the hero",
        "predicate": "trying to remember the capital of Australia.",
        "text": "Either the hitchhikers or the hero %is,are,am% trying to remember the capital of Australia.",
        "conj1_agr": "3P",
        "conj2_agr": "3S",
        "dataType": "critical",
        "cond": "3P_or_3S"
    },
    {
        "id": 61,
        "conj1": "the mermaids",
        "conj2": "the meteorologist",
        "predicate": "hitting the jackpot.",
        "text": "Either the mermaids or the meteorologist %is,are,am% hitting the jackpot.",
        "conj1_agr": "3P",
        "conj2_agr": "3S",
        "dataType": "critical",
        "cond": "3P_or_3S"
    },
    {
        "id": 62,
        "conj1": "the ogres",
        "conj2": "the sailor",
        "predicate": "dominating in League of Legends.",
        "text": "Either the ogres or the sailor %is,are,am% dominating in League of Legends.",
        "conj1_agr": "3P",
        "conj2_agr": "3S",
        "dataType": "critical",
        "cond": "3P_or_3S"
    },
    {
        "id": 63,
        "conj1": "the androids",
        "conj2": "the waitress",
        "predicate": "learning a new language.",
        "text": "Either the androids or the waitress %is,are,am% learning a new language.",
        "conj1_agr": "3P",
        "conj2_agr": "3S",
        "dataType": "critical",
        "cond": "3P_or_3S"
    },
    {
        "id": 64,
        "conj1": "the street performers",
        "conj2": "the scientist",
        "predicate": "dancing the macarena.",
        "text": "Either the street performers or the scientist %is,are,am% dancing the macarena.",
        "conj1_agr": "3P",
        "conj2_agr": "3S",
        "dataType": "critical",
        "cond": "3P_or_3S"
    },
    {
        "id": 65,
        "conj1": "the Real Housewives of Orlando",
        "conj2": "the graduate students",
        "predicate": "moving to Nairobi.",
        "text": "Either the Real Housewives of Orlando or the graduate students %is,are,am% moving to Nairobi.",
        "conj1_agr": "3P",
        "conj2_agr": "3P",
        "dataType": "critical",
        "cond": "3P_or_3P"
    },
    {
        "id": 66,
        "conj1": "the tailors",
        "conj2": "the leprechauns",
        "predicate": "attending a lecture on Jane Austen.",
        "text": "Either the tailors or the leprechauns %is,are,am% attending a lecture on Jane Austen.",
        "conj1_agr": "3P",
        "conj2_agr": "3P",
        "dataType": "critical",
        "cond": "3P_or_3P"
    },
    {
        "id": 67,
        "conj1": "the pianists",
        "conj2": "the sales associates",
        "predicate": "adopting a family of kittens.",
        "text": "Either the pianists or the sales associates %is,are,am% adopting a family of kittens.",
        "conj1_agr": "3P",
        "conj2_agr": "3P",
        "dataType": "critical",
        "cond": "3P_or_3P"
    },
    {
        "id": 68,
        "conj1": "the gargoyle",
        "conj2": "the graphic designers",
        "predicate": "making a toy at Build-A-Bear.",
        "text": "Either the gargoyle or the graphic designers %is,are,am% making a toy at Build-A-Bear.",
        "conj1_agr": "3P",
        "conj2_agr": "3P",
        "dataType": "critical",
        "cond": "3P_or_3P"
    },
    {
        "id": 69,
        "conj1": "the pharmacists",
        "conj2": "the werewolves",
        "predicate": "pleading with the Prime Minister.",
        "text": "Either the pharmacists or the werewolves %is,are,am% pleading with the Prime Minister.",
        "conj1_agr": "3P",
        "conj2_agr": "3P",
        "dataType": "critical",
        "cond": "3P_or_3P"
    },
    {
        "id": 70,
        "conj1": "I",
        "conj2": "null",
        "predicate": "feeding my firstborn.",
        "text": "I %is,are,am% feeding my firstborn.",
        "conj1_agr": "1S",
        "conj2_agr": "null",
        "dataType": "filler_am",
        "cond": "1S"
    },
    {
        "id": 71,
        "conj1": "I",
        "conj2": "null",
        "predicate": "eating my lunch.",
        "text": "I %is,are,am% eating my lunch.",
        "conj1_agr": "1S",
        "conj2_agr": "null",
        "dataType": "filler_am",
        "cond": "1S"
    },
    {
        "id": 72,
        "conj1": "I",
        "conj2": "null",
        "predicate": "getting my car detailed.",
        "text": "I %is,are,am% getting my car detailed.",
        "conj1_agr": "1S",
        "conj2_agr": "null",
        "dataType": "filler_am",
        "cond": "1S"
    },
    {
        "id": 73,
        "conj1": "I",
        "conj2": "null",
        "predicate": "reheating my day-old fries.",
        "text": "I %is,are,am% reheating my day-old fries.",
        "conj1_agr": "1S",
        "conj2_agr": "null",
        "dataType": "filler_am",
        "cond": "1S"
    },
    {
        "id": 74,
        "conj1": "I",
        "conj2": "null",
        "predicate": "conversing with my mother.",
        "text": "I %is,are,am% conversing with my mother.",
        "conj1_agr": "1S",
        "conj2_agr": "null",
        "dataType": "filler_am",
        "cond": "1S"
    },
    {
        "id": 75,
        "conj1": "I",
        "conj2": "null",
        "predicate": "wishing on a shooting star.",
        "text": "I %is,are,am% wishing on a shooting star.",
        "conj1_agr": "1S",
        "conj2_agr": "null",
        "dataType": "filler_am",
        "cond": "1S"
    },
    {
        "id": 76,
        "conj1": "I",
        "conj2": "null",
        "predicate": "helping my friend win back their ex.",
        "text": "I %is,are,am% helping my friend win back their ex.",
        "conj1_agr": "1S",
        "conj2_agr": "null",
        "dataType": "filler_am",
        "cond": "1S"
    },
    {
        "id": 77,
        "conj1": "I",
        "conj2": "null",
        "predicate": "getting my ears pierced.",
        "text": "I %is,are,am% getting my ears pierced.",
        "conj1_agr": "1S",
        "conj2_agr": "null",
        "dataType": "filler_am",
        "cond": "1S"
    },
    {
        "id": 78,
        "conj1": "I",
        "conj2": "null",
        "predicate": "cooking dinner for my dog.",
        "text": "I %is,are,am% cooking dinner for my dog.",
        "conj1_agr": "1S",
        "conj2_agr": "null",
        "dataType": "filler_am",
        "cond": "1S"
    },
    {
        "id": 79,
        "conj1": "I",
        "conj2": "null",
        "predicate": "teaching my cat Spanish.",
        "text": "I %is,are,am% teaching my cat Spanish.",
        "conj1_agr": "1S",
        "conj2_agr": "null",
        "dataType": "filler_am",
        "cond": "1S"
    },
    {
        "id": 80,
        "conj1": "I",
        "conj2": "null",
        "predicate": "weeding my garden.",
        "text": "I %is,are,am% weeding my garden.",
        "conj1_agr": "1S",
        "conj2_agr": "null",
        "dataType": "filler_am",
        "cond": "1S"
    },
    {
        "id": 81,
        "conj1": "I",
        "conj2": "null",
        "predicate": "working on my PhD.",
        "text": "I %is,are,am% working on my PhD.",
        "conj1_agr": "1S",
        "conj2_agr": "null",
        "dataType": "filler_am",
        "cond": "1S"
    },
    {
        "id": 82,
        "conj1": "I",
        "conj2": "null",
        "predicate": "celebrating my sibling's birthday.",
        "text": "I %is,are,am% celebrating my sibling's birthday.",
        "conj1_agr": "1S",
        "conj2_agr": "null",
        "dataType": "filler_am",
        "cond": "1S"
    },
    {
        "id": 83,
        "conj1": "I",
        "conj2": "null",
        "predicate": "giving my partner a high-five.",
        "text": "I %is,are,am% giving my partner a high-five.",
        "conj1_agr": "1S",
        "conj2_agr": "null",
        "dataType": "filler_am",
        "cond": "1S"
    },
    {
        "id": 84,
        "conj1": "I",
        "conj2": "null",
        "predicate": "laughing at myself in the mirror.",
        "text": "I %is,are,am% laughing at myself in the mirror.",
        "conj1_agr": "1S",
        "conj2_agr": "null",
        "dataType": "filler_am",
        "cond": "1S"
    },
    {
        "id": 85,
        "conj1": "I",
        "conj2": "null",
        "predicate": "helping my sister-in-law with her art history paper.",
        "text": "I %is,are,am% helping my sister-in-law with her art history paper.",
        "conj1_agr": "1S",
        "conj2_agr": "null",
        "dataType": "filler_am",
        "cond": "1S"
    },
    {
        "id": 86,
        "conj1": "I",
        "conj2": "null",
        "predicate": "trying to find my Halloween candy.",
        "text": "I %is,are,am% trying to find my Halloween candy.",
        "conj1_agr": "1S",
        "conj2_agr": "null",
        "dataType": "filler_am",
        "cond": "1S"
    },
    {
        "id": 87,
        "conj1": "I",
        "conj2": "null",
        "predicate": "working on my third novel.",
        "text": "I %is,are,am% working on my third novel.",
        "conj1_agr": "1S",
        "conj2_agr": "null",
        "dataType": "filler_am",
        "cond": "1S"
    },
    {
        "id": 88,
        "conj1": "I",
        "conj2": "null",
        "predicate": "picking the onion out of my tomato soup.",
        "text": "I %is,are,am% picking the onion out of my tomato soup.",
        "conj1_agr": "1S",
        "conj2_agr": "null",
        "dataType": "filler_am",
        "cond": "1S"
    },
    {
        "id": 89,
        "conj1": "I",
        "conj2": "null",
        "predicate": "rearranging my bedroom furniture.",
        "text": "I %is,are,am% rearranging my bedroom furniture.",
        "conj1_agr": "1S",
        "conj2_agr": "null",
        "dataType": "filler_am",
        "cond": "1S"
    },
    {
        "id": 90,
        "conj1": "Oliver",
        "conj2": "we",
        "predicate": "designing tote bags for the funeral home.",
        "text": "Both Oliver and we %is,are,am% designing tote bags for the funeral home.",
        "conj1_agr": "3S",
        "conj2_agr": "1P",
        "dataType": "filler_are",
        "cond": "3S_and_1P"
    },
    {
        "id": 91,
        "conj1": "Rachel",
        "conj2": "the fishers",
        "predicate": "planning a trip to Jupiter.",
        "text": "Both Rachel and the fishers %is,are,am% planning a trip to Jupiter.",
        "conj1_agr": "3S",
        "conj2_agr": "3P",
        "dataType": "filler_are",
        "cond": "3S_and_3P"
    },
    {
        "id": 92,
        "conj1": "the stunt doubles",
        "conj2": "the dog trainers",
        "predicate": "reworking the building's evacuation plans.",
        "text": "Both the stunt doubles and the dog trainers %is,are,am% reworking the building's evacuation plans.",
        "conj1_agr": "3S",
        "conj2_agr": "3P",
        "dataType": "filler_are",
        "cond": "3S_and_3P"
    },
    {
        "id": 93,
        "conj1": "we",
        "conj2": "the lifeguards",
        "predicate": "blowing kisses to the Queen.",
        "text": "Both we and the lifeguards %is,are,am% blowing kisses to the Queen.",
        "conj1_agr": "1P",
        "conj2_agr": "3P",
        "dataType": "filler_are",
        "cond": "1P_and_3P"
    },
    {
        "id": 94,
        "conj1": "Katherine",
        "conj2": "Quincy",
        "predicate": "failing Spanish class.",
        "text": "Both Katherine and Quincy %is,are,am% failing Spanish class.",
        "conj1_agr": "3S",
        "conj2_agr": "3S",
        "dataType": "filler_are",
        "cond": "3S_and_3S"
    },
    {
        "id": 95,
        "conj1": "Quinn",
        "conj2": "we",
        "predicate": "brushing a cat.",
        "text": "Both Quinn and we %is,are,am% brushing a cat.",
        "conj1_agr": "3S",
        "conj2_agr": "1P",
        "dataType": "filler_are",
        "cond": "3S_and_1P"
    },
    {
        "id": 96,
        "conj1": "Natalie",
        "conj2": "I",
        "predicate": "reading the dictionary cover to cover.",
        "text": "Both Natalie and I %is,are,am% reading the dictionary cover to cover.",
        "conj1_agr": "3S",
        "conj2_agr": "1S",
        "dataType": "filler_are",
        "cond": "3S_and_1S"
    },
    {
        "id": 97,
        "conj1": "we",
        "conj2": "the shoppers",
        "predicate": "playing Scrabble.",
        "text": "Both we and the shoppers %is,are,am% playing Scrabble.",
        "conj1_agr": "1P",
        "conj2_agr": "3P",
        "dataType": "filler_are",
        "cond": "1P_and_3P"
    },
    {
        "id": 98,
        "conj1": "Faith",
        "conj2": "I",
        "predicate": "participating in a beauty pageant.",
        "text": "Both Faith and I %is,are,am% participating in a beauty pageant.",
        "conj1_agr": "3S",
        "conj2_agr": "1S",
        "dataType": "filler_are",
        "cond": "3S_and_1S"
    },
    {
        "id": 99,
        "conj1": "Emily",
        "conj2": "I",
        "predicate": "waving through a window.",
        "text": "Both Emily and I %is,are,am% waving through a window.",
        "conj1_agr": "3S",
        "conj2_agr": "1S",
        "dataType": "filler_are",
        "cond": "3S_and_1S"
    },
    {
        "id": 100,
        "conj1": "Hannah",
        "conj2": "the Martians",
        "predicate": "putting together a heist.",
        "text": "Both Hannah and the Martians %is,are,am% putting together a heist.",
        "conj1_agr": "3S",
        "conj2_agr": "3P",
        "dataType": "filler_are",
        "cond": "3S_and_3P"
    },
    {
        "id": 101,
        "conj1": "I",
        "conj2": "we",
        "predicate": "traveling down Route 66.",
        "text": "Both I and we %is,are,am% traveling down Route 66.",
        "conj1_agr": "1S",
        "conj2_agr": "1P",
        "dataType": "filler_are",
        "cond": "1S_and_1P"
    },
    {
        "id": 102,
        "conj1": "Nora",
        "conj2": "Jasmine",
        "predicate": "drinking black coffee.",
        "text": "Both Nora and Jasmine %is,are,am% drinking black coffee.",
        "conj1_agr": "3S",
        "conj2_agr": "3S",
        "dataType": "filler_are",
        "cond": "3S_and_3S"
    },
    {
        "id": 103,
        "conj1": "Ximena",
        "conj2": "I",
        "predicate": "seeking external validation.",
        "text": "Both Ximena and I %is,are,am% seeking external validation.",
        "conj1_agr": "3S",
        "conj2_agr": "1S",
        "dataType": "filler_are",
        "cond": "3S_and_1S"
    },
    {
        "id": 104,
        "conj1": "Frank",
        "conj2": "the janitors",
        "predicate": "purchasing new phones.",
        "text": "Both Frank and the janitors %is,are,am% purchasing new phones.",
        "conj1_agr": "3S",
        "conj2_agr": "3P",
        "dataType": "filler_are",
        "cond": "3S_and_3P"
    },
    {
        "id": 105,
        "conj1": "we",
        "conj2": "Gabriel",
        "predicate": "painting over the original Mona Lisa.",
        "text": "Both we and Gabriel %is,are,am% painting over the original Mona Lisa.",
        "conj1_agr": "1P",
        "conj2_agr": "3S",
        "dataType": "filler_are",
        "cond": "1P_and_3S"
    },
    {
        "id": 106,
        "conj1": "I",
        "conj2": "the hairdressers",
        "predicate": "following a Bob Ross tutorial.",
        "text": "Both I and the hairdressers %is,are,am% following a Bob Ross tutorial.",
        "conj1_agr": "1S",
        "conj2_agr": "3P",
        "dataType": "filler_are",
        "cond": "1S_and_3P"
    },
    {
        "id": 107,
        "conj1": "the detectives",
        "conj2": "the actresses",
        "predicate": "helping remove lice from a child's hair.",
        "text": "Both the detectives and the actresses %is,are,am% helping remove lice from a child's hair.",
        "conj1_agr": "1S",
        "conj2_agr": "3P",
        "dataType": "filler_are",
        "cond": "1S_and_3P"
    },
    {
        "id": 108,
        "conj1": "we",
        "conj2": "I",
        "predicate": "building a model train set.",
        "text": "Both we and I %is,are,am% building a model train set.",
        "conj1_agr": "1P",
        "conj2_agr": "1S",
        "dataType": "filler_are",
        "cond": "1P_and_1S"
    },
    {
        "id": 109,
        "conj1": "I",
        "conj2": "the millionaires",
        "predicate": "meditating at the airport.",
        "text": "Both I and the millionaires %is,are,am% meditating at the airport.",
        "conj1_agr": "1S",
        "conj2_agr": "3P",
        "dataType": "filler_are",
        "cond": "1S_and_3P"
    },
    {
        "id": 110,
        "conj1": "Willa",
        "conj2": "null",
        "predicate": "drinking a Diet Coke in the shower.",
        "text": "Willa %is,are,am% drinking a Diet Coke in the shower.",
        "conj1_agr": "3S",
        "conj2_agr": "null",
        "dataType": "filler_is",
        "cond": "3S"
    },
    {
        "id": 111,
        "conj1": "Rose",
        "conj2": "null",
        "predicate": "opening the fridge.",
        "text": "Rose %is,are,am% opening the fridge.",
        "conj1_agr": "3S",
        "conj2_agr": "null",
        "dataType": "filler_is",
        "cond": "3S"
    },
    {
        "id": 112,
        "conj1": "Uma",
        "conj2": "null",
        "predicate": "trying to decipher the youths' slang.",
        "text": "Uma %is,are,am% trying to decipher the youths' slang.",
        "conj1_agr": "3S",
        "conj2_agr": "null",
        "dataType": "filler_is",
        "cond": "3S"
    },
    {
        "id": 113,
        "conj1": "Zachary",
        "conj2": "null",
        "predicate": "looking for a clean pair of shorts.",
        "text": "Zachary %is,are,am% looking for a clean pair of shorts.",
        "conj1_agr": "3S",
        "conj2_agr": "null",
        "dataType": "filler_is",
        "cond": "3S"
    },
    {
        "id": 114,
        "conj1": "Holly",
        "conj2": "null",
        "predicate": "folding napkins for the wedding.",
        "text": "Holly %is,are,am% folding napkins for the wedding.",
        "conj1_agr": "3S",
        "conj2_agr": "null",
        "dataType": "filler_is",
        "cond": "3S"
    },
    {
        "id": 115,
        "conj1": "Jack",
        "conj2": "null",
        "predicate": "building a home.",
        "text": "Jack %is,are,am% building a home.",
        "conj1_agr": "3S",
        "conj2_agr": "null",
        "dataType": "filler_is",
        "cond": "3S"
    },
    {
        "id": 116,
        "conj1": "Isaac",
        "conj2": "null",
        "predicate": "planning to move to Kansas.",
        "text": "Isaac %is,are,am% planning to move to Kansas.",
        "conj1_agr": "3S",
        "conj2_agr": "null",
        "dataType": "filler_is",
        "cond": "3S"
    },
    {
        "id": 117,
        "conj1": "Charlie",
        "conj2": "null",
        "predicate": "focusing on the task at hand.",
        "text": "Charlie %is,are,am% focusing on the task at hand.",
        "conj1_agr": "3S",
        "conj2_agr": "null",
        "dataType": "filler_is",
        "cond": "3S"
    },
    {
        "id": 118,
        "conj1": "Xavier",
        "conj2": "null",
        "predicate": "eating without utensils.",
        "text": "Xavier %is,are,am% eating without utensils.",
        "conj1_agr": "3S",
        "conj2_agr": "null",
        "dataType": "filler_is",
        "cond": "3S"
    },
    {
        "id": 119,
        "conj1": "Grace",
        "conj2": "null",
        "predicate": "hoping for a miracle.",
        "text": "Grace %is,are,am% hoping for a miracle.",
        "conj1_agr": "3S",
        "conj2_agr": "null",
        "dataType": "filler_is",
        "cond": "3S"
    },
    {
        "id": 120,
        "conj1": "Amelia",
        "conj2": "null",
        "predicate": "trying to cleanse the negative energy in the house.",
        "text": "Amelia %is,are,am% trying to cleanse the negative energy in the house.",
        "conj1_agr": "3S",
        "conj2_agr": "null",
        "dataType": "filler_is",
        "cond": "3S"
    },
    {
        "id": 121,
        "conj1": "Henry",
        "conj2": "null",
        "predicate": "arranging a bouquet.",
        "text": "Henry %is,are,am% arranging a bouquet.",
        "conj1_agr": "3S",
        "conj2_agr": "null",
        "dataType": "filler_is",
        "cond": "3S"
    },
    {
        "id": 122,
        "conj1": "Kayla",
        "conj2": "null",
        "predicate": "reading the magazine.",
        "text": "Kayla %is,are,am% reading the magazine.",
        "conj1_agr": "3S",
        "conj2_agr": "null",
        "dataType": "filler_is",
        "cond": "3S"
    },
    {
        "id": 123,
        "conj1": "Naomi",
        "conj2": "null",
        "predicate": "catching the train uptown.",
        "text": "Naomi %is,are,am% catching the train uptown.",
        "conj1_agr": "3S",
        "conj2_agr": "null",
        "dataType": "filler_is",
        "cond": "3S"
    },
    {
        "id": 124,
        "conj1": "Penelope",
        "conj2": "null",
        "predicate": "trying to hail a taxi.",
        "text": "Penelope %is,are,am% trying to hail a taxi.",
        "conj1_agr": "3S",
        "conj2_agr": "null",
        "dataType": "filler_is",
        "cond": "3S"
    },
    {
        "id": 125,
        "conj1": "Ryan",
        "conj2": "null",
        "predicate": "accusing the actor of being a nepo baby.",
        "text": "Ryan %is,are,am% accusing the actor of being a nepo baby.",
        "conj1_agr": "3S",
        "conj2_agr": "null",
        "dataType": "filler_is",
        "cond": "3S"
    },
    {
        "id": 126,
        "conj1": "Matthew",
        "conj2": "null",
        "predicate": "texting the group chat about the tea.",
        "text": "Matthew %is,are,am% texting the group chat about the tea.",
        "conj1_agr": "3S",
        "conj2_agr": "null",
        "dataType": "filler_is",
        "cond": "3S"
    },
    {
        "id": 127,
        "conj1": "Tristan",
        "conj2": "null",
        "predicate": "working on a new iPad.",
        "text": "Tristan %is,are,am% working on a new iPad.",
        "conj1_agr": "3S",
        "conj2_agr": "null",
        "dataType": "filler_is",
        "cond": "3S"
    },
    {
        "id": 128,
        "conj1": "Finn",
        "conj2": "null",
        "predicate": "going to the Broadway show.",
        "text": "Finn %is,are,am% going to the Broadway show.",
        "conj1_agr": "3S",
        "conj2_agr": "null",
        "dataType": "filler_is",
        "cond": "3S"
    },
    {
        "id": 129,
        "conj1": "Olive",
        "conj2": "null",
        "predicate": "shopping online for linen shirts.",
        "text": "Olive %is,are,am% shopping online for linen shirts.",
        "conj1_agr": "3S",
        "conj2_agr": "null",
        "dataType": "filler_is",
        "cond": "3S"
    }
]